version: "3.8"

services:
  backend:
    container_name: fpf_backend
    build: 
      context: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
  frontend:
    container_name: fpf_frontend
    build: 
      context: ./frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
  db:
    container_name: estudante_db
    image: mysql:8
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_db_estudante:/var/lib/mysql
      - mysql_db_estudante_config:/etc/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes:
  mysql_db_estudante:
  mysql_db_estudante_config: